version: "3"

networks:
  backend:
    name: laradock_backend

volumes:
  namenode:
  datanode:

services:

  ########## Hadoop Name Node ##########
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hive.env
    ports:
      - "9870:9870"
    networks:
      - backend

  ########## Hadoop Data Node ##########
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - backend

  ########## Hive ##########
  hive:
    image: gindow/hive
    env_file:
      - ./hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - backend

  ########## Hive Meta Store ##########
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:8020 datanode:9866 hive-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - backend

  ########## Hive Postgresql ##########
  hive-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      - backend

  ########## Presto ##########
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "9090:8080"
    networks:
      - backend
